resource_group_name    = "rg-kv_terraform_pr"
location               = "West Europe"
keyvault_name          = "testterraformkvpr"
secret_name            = "DatabasePassword"
secret_value           = "@Aa123456789!"